=== qwear0/L2Kingdom/data/Skills/Active/.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "selfId": {
                "type": "integer"
            },
            "template": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "passive": {
                        "type": "boolean"
                    },
                    "spell": {
                        "type": "boolean"
                    },
                    "distance": {
                        "type": "integer"
                    }
                },
                "required": [
                    "name",
                    "passive",
                    "spell",
                    "distance"
                ]
            },
            "time": {
                "type": "object",
                "properties": {
                    "hitTime": {
                        "type": "integer"
                    },
                    "reuse": {
                        "type": "integer"
                    },
                    "buff": {
                        "type": "integer"
                    }
                },
                "required": [
                    "hitTime",
                    "reuse",
                    "buff"
                ]
            },
            "levels": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "level": {
                            "type": "integer"
                        },
                        "power": {
                            "type": "number"
                        },
                        "mp": {
                            "type": "integer"
                        },
                        "hp": {
                            "type": "integer"
                        },
                        "itemId": {
                            "type": "integer"
                        },
                        "itemCount": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "level",
                        "power",
                        "mp",
                        "hp",
                        "itemId",
                        "itemCount"
                    ]
                }
            }
        },
        "required": [
            "selfId",
            "template",
            "time",
            "levels"
        ]
    }
}

=== qwear0/L2Kingdom/data/Skills/Passive/c4_fishing.json
[
    {
        "selfId": 1315,
        "template": {
            "name": "Fishing Expertise",
            "passive": true,
            "spell": false,
            "distance": 0
        },
        "time": {
            "hitTime": 0,
            "reuse": 0,
            "buff": 0
        },
        "levels": [
            {
                "level": 1,
                "power": 0.66,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 2,
                "power": 0.9375,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 3,
                "power": 1.26,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 4,
                "power": 1.55,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 5,
                "power": 1.7,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 6,
                "power": 1.85,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 7,
                "power": 2.0,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 8,
                "power": 2.15,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 9,
                "power": 2.3,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 10,
                "power": 2.45,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 11,
                "power": 2.6,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 12,
                "power": 2.75,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 13,
                "power": 2.9,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 14,
                "power": 3.05,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 15,
                "power": 3.2,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 16,
                "power": 3.35,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 17,
                "power": 3.5,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 18,
                "power": 3.65,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 19,
                "power": 3.8,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 20,
                "power": 3.95,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 21,
                "power": 4.1,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 22,
                "power": 4.25,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 23,
                "power": 4.4,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 24,
                "power": 4.55,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 25,
                "power": 4.7,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 26,
                "power": 4.85,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            },
            {
                "level": 27,
                "power": 5.0,
                "mp": 0,
                "hp": 0,
                "itemId": 0,
                "itemCount": 0
            }
        ]
    }
]
